name: "Notify the deployment"
description: "Send the deployment status to MS teams"
inputs:
  webhook-url:
    required: true
  sha:
    required: true
  status:
    required: true
  github-run-url:
    required: true
  actor:
    required: true
  service-name:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - shell: bash
      run:
        python notify-deployment-status.py
